### PR TITLE
add clipboard manager plugin

### PR DESCRIPTION
**Pull request by rpaciorek**
add configurable clipboard manager plugin with option to save clipboard history

### CODE REVIEW

**Review by ifohancroft — CHANGES_REQUESTED** [review]
Wouldn't the cache directory be more appropriate for the history file?
Also, can you please utilize the XDG dirs instead of hardcoding the path to the directory. Let me know if for some reason that's not possible with fbpanel though.

**Comment by rpaciorek** [comment]
This is sample config file. It seems to me that fbpanel doesn't support variables in config file.

Cache is rather intended for easy to reproduce stuff, but clipboard history for some user is important, especially that this plugin support permanent entry (switched by right mouse button click), so I think config dir is better than cache for this.

**Comment by ifohancroft** [comment]
Sorry, I missed the fact that it's a sample config file.
Also, fair point about the clipboard history being important to people - then perhaps the data directory (.local/share/fbpanel/)? Let me know if you disagree.

**Comment by rpaciorek** [comment]
`.local/share/fbpanel` might be ok, but need change (or create?) install script to create them ... or maybe create it from `write_history_to_file` function

`.config` is used to store misc "history" info (eg. search and replace, opened files, etc) by other programs (eg. kate, okular, gimp), so use it is not unusual

**Comment by ifohancroft** [comment]
> `.local/share/fbpanel` might be ok, but need change (or create?) install script to create them ... or maybe create it from `write_history_to_file` function

I did not understand this first part.

> `.config` is used to store misc "history" info (eg. search and replace, opened files, etc) by other programs (eg. kate, okular, gimp), so use it is not unusual

That's true. However, I do not agree with them on this, I think it's the wrong directory. Anyway, I am acceping your PR, we can always change the path at a later date. Do late me know what you meant with your first sentence though.

**Comment by rpaciorek** [comment]
> > `.local/share/fbpanel` might be ok, but need change (or create?) install script to create them ... or maybe create it from `write_history_to_file` function
> 
> I did not understand this first part.

1. `fopen()` with `w` mode can create new file, but not missing directories in path to this file
2. `.config/fbpanel` is created in some way
3. but `.local/share/fbpanel` do not exist
4. so if we use `.local/share/fbpanel` in default config we should create it in some way ...

**Comment by ifohancroft** [comment]
Ah! Yes. I think fbpanel should create both .config/fbpanel, .local/share/fbpanel, as well as .cache/fbpanel (or at least those directories it would use, if not all of them)

**Pull request merged**
