### PR TITLE
add "dir" entry for "menu" plugin

### PR DESCRIPTION
**Pull request by rpaciorek**
allow add directory listing menu entry to menu plugin

### CODE REVIEW

**Review by ifohancroft — CHANGES_REQUESTED** [review]
Would you please change NOTATKI to NOTES (unless I am mistaken about the meaning of the word).
Also, is it possible (I am genuinely asking) to not hardcode konqueror and kate?

**Review by ifohancroft — CHANGES_REQUESTED** [review]
I meant not hardcoding a specific editor, not changing the hardcoding to another

**Comment by rpaciorek** [comment]
I changed to `xdg-open` - it still hardcoded specific program, but I don't better idea.

BTW this editor (and many other info - icons, programs, network interface) are hardcoded in this config file ...

**Review by ifohancroft — CHANGES_REQUESTED** [review]
@rpaciorek Yeah, I feel like xdg-open is the safest bet.

Thank you! I'd look into that.

Ideally, I'd like to get the PRs sent to the original fbpanel merged in here, then have it ported to GTK4, then make a new build system (GNU Autotools), then start fixing stuff.

**Review by ifohancroft — APPROVED** [review]

**Pull request merged**
